### ISSUE TITLE
 Why can't it detect qca8337 switch chip？

### ISSUE THREAD

**Issue by zimiao815** [siklu/qca-ssdk#1]
hi   Why can't it detect qca8337 switch chip？
cpu:IPQ5018
borad : AP-MP03.3

`

mdio0: mdio@88000 {
			status = "ok";
			ethernet-phy@0 {
				reg = <7>;
			};
		};

		mdio1: mdio@90000 {
			status = "ok";
			pinctrl-0 = <&mdio1_pins>;
			pinctrl-names = "default";
			phy-reset-gpio = <&tlmm 23 0>;
			ethernet-phy@0 {
				reg = <0>;
			};

			ethernet-phy@1 {
				reg = <1>;
			};

			ethernet-phy@2 {
				reg = <2>;
			};

			ethernet-phy@3 {
				reg = <3>;
			};

		};

		ess-instance {
			num_devices = <0x2>;
			ess-switch@0x39c00000 {
				compatible = "qcom,ess-switch-ipq50xx";
				device_id = <0>;
				switch_mac_mode = <0xf>; /* mac mode for uniphy instance*/
				cmnblk_clk = "internal_96MHz"; /* cmnblk clk*/
				qcom,port_phyinfo {
					port@0 {
						port_id = <1>;
						phy_address = <7>;
						mdiobus = <&mdio0>;
						phy_dac= [0000001000000010];
					};
					port@1 {
						port_id = <2>;
						forced-speed = <1000>;
						forced-duplex = <1>;
					};
				};
				led_source@0 {
					source = <0>;
					mode = "normal";
					speed = "all";
					blink_en = "enable";
					active = "high";
				};
			};
			ess-switch1@1{
				compatible = "qcom,ess-switch-qca83xx";
				device_id = <1>;
				switch_access_mode = "mdio";
				mdio-bus = <&mdio1>;
				reset_gpio = <0x27>;
				switch_cpu_bmp = <0x40>;  /* cpu port bitmap */
				switch_lan_bmp = <0x0e>; /* lan port bitmap */
				switch_wan_bmp = <0x30>;  /* wan port bitmap */
				qca,ar8327-initvals = <
						0x00004 0x7600000   /* PAD0_MODE */
						0x00008 0x1000000   /* PAD5_MODE */
						0x0000c 0x80        /* PAD6_MODE */
						0x00010 0x2613a0    /* PORT6 FORCE MODE*/
						0x000e4 0xaa545     /* MAC_POWER_SEL */
						0x000e0 0xc74164de  /* SGMII_CTRL */
						0x0007c 0x4e        /* PORT0_STATUS */
						0x00094 0x4e        /* PORT6_STATUS */
				>;
				qcom,port_phyinfo {
					port@0 {
						port_id = <1>;
						phy_address = <0>;
					};
					port@1 {
						port_id = <2>;
						phy_address = <1>;
					};
					port@2 {
						port_id = <3>;
						phy_address = <2>;
					};
					port@3 {
						port_id = <4>;
						phy_address = <3>;
					};
				};
			};
		};

		wifi0: wifi@c000000 {
			status = "ok";
		};

		dp1 {
			device_type = "network";
			compatible = "qcom,nss-dp";
			clocks = <&gcc GCC_SNOC_GMAC0_AXI_CLK>;
			clock-names = "nss-snoc-gmac-axi-clk";
			qcom,id = <1>;
			reg = <0x39C00000 0x10000>;
			interrupts = <GIC_SPI 101 IRQ_TYPE_LEVEL_HIGH>;
			qcom,mactype = <2>;
			qcom,link-poll = <1>;
			qcom,phy-mdio-addr = <7>;
			mdio-bus = <&mdio0>;
			local-mac-address = [000000000000];
			phy-mode = "sgmii";
		};

		dp2 {
			device_type = "network";
			compatible = "qcom,nss-dp";
			clocks = <&gcc GCC_SNOC_GMAC1_AXI_CLK>;
			clock-names = "nss-snoc-gmac-axi-clk";
			qcom,id = <2>;
			reg = <0x39D00000 0x10000>;
			interrupts = <GIC_SPI 109 IRQ_TYPE_LEVEL_HIGH>;
			qcom,mactype = <2>;
			//qcom,link-poll = <1>;
			//qcom,phy-mdio-addr = <28>;
			//mdio-bus = <&mdio1>;
			local-mac-address = [000000000000];
			phy-mode = "sgmii";
		};`

`
[   16.246702] ssdk_switch_device_num_init[1159]:INFO:ess-switch dts node number: 2

[   16.246746] ssdk_dt_get_switch_node[970]:INFO:ess-switch DT exist!

[   16.253160] ssdk_dt_parse_access_mode[856]:INFO:switch_access_mode: local bus

[   16.259183] ssdk_dt_parse_access_mode[869]:INFO:switchreg_base_addr: 0x39c00000

[   16.266365] ssdk_dt_parse_access_mode[870]:INFO:switchreg_size: 0x200000

[   16.273468] ssdk_dt_parse_mac_mode[295]:INFO:mac mode = 0xf

[   16.280421] ssdk_dt_parse_mac_mode[301]:INFO:mac mode1 doesn't exit!

[   16.285706] ssdk_dt_parse_mac_mode[310]:INFO:mac mode2 doesn't exit!

[   16.292359] ssdk_dt_parse_port_bmp[757]:INFO:port_bmp doesn't exist!

[   16.298675] ssdk_dt_parse_uniphy[332]:INFO:ess-uniphy DT exist!

[   16.304983] ssdk_dt_parse_led[943]:INFO:current dts led_source_num is 1

[   16.310649] ssdk_plat_init start

[   18.725890] ssdk_mp_reset_init[739]:INFO:MP reset successfully!1

[   18.725953] ssdk_gcc_clock_init[1011]:INFO:SSDK gcc clock init successfully!

[   18.731672] mpge_phy_api_ops_init[1089]:INFO:qca probe mpge phy driver succeeded!

[   18.738398] mpge_phy_dac_set[917]:INFO:phy mdac is set as 0x10

[   18.745407] mpge_phy_dac_set[929]:INFO:phy edac is set as 0x10

[   18.751156] regi_init[3557]:INFO:Initializing SCOMPHY!

[   19.889904] _adpt_mp_uniphy_clk_output_ctrl_set[236]:INFO:uniphy will output clock as 25000000Hz

[   19.890017] ssdk_led_init[152]:INFO:ssdk_led_mode:3, ssdk_led_map:ffc, ssdk_led_src_id:0

[   19.897879] ssdk_switch_register[1683]:INFO:Chip version 0xee

[   19.905850] qca_link_polling_select[1307]:INFO:link-polling-required node does not exist

[   19.911462] ssdk_switch_register[1717]:INFO:polling is selected

[   19.919633] regi_init[3567]:INFO:Initializing SCOMPHY Done!!

[   19.925294] ssdk_dt_get_switch_node[970]:INFO:ess-switch DT exist!

[   19.931187] ssdk_dt_parse_access_mode[856]:INFO:switch_access_mode: mdio

[   19.937168] ssdk_dt_parse_mac_mode[292]:INFO:mac mode doesn't exit!

[   19.944011] ssdk_dt_parse_mac_mode[301]:INFO:mac mode1 doesn't exit!

[   19.950013] ssdk_dt_parse_mac_mode[310]:INFO:mac mode2 doesn't exit!

[   19.956640] ssdk_dt_parse[1061]:INFO:switch node is qca83xx!

[   19.962936] ssdk_plat_init start

[   19.968943] regi_init[3594]:INFO:qca-ssdk module init, no device found!

`
the last line "no device found!"
Then I added some logs  ：

`
[   19.983104] ssdk_plat_init start

[   19.988778] ssdk_plat_init!/n

[   19.991954] ssdk_driver_register!/n

[   19.994971] qca_ar8216_mii_read chip_ver=255!

[   19.998137] qca_ssdk_port_bmp_get port_bmp=62!

[   20.002485] hsl_phyid_get phy_id=-1!

[   20.006836] hsl_phyid_get phy_id=-1!

[   20.010554] hsl_phyid_get phy_id=-1!

[   20.014114] hsl_phyid_get phy_id=-1!

[   20.017685] hsl_phyid_get phy_id=-1!

[   20.021208] chip_ver_get!/nregi_init[3646]:INFO:qca-ssdk module init, no device found!

`
chip_ver=255 is error ？

Do you know what the problem is？
thank you very much！！！

**Comment by anjanadrip** [comment]
Can u please post the changes done to resolve this issue? We are also facing the same issue in ipq8072a based board for the switch.

**Comment by anjanadrip** [comment]
@zimiao815
